### ISSUE TITLE
建议增加浏览器兼容性

### ISSUE THREAD

**Issue by hanyoujun** [fantastic-admin/basic#20]
src/components/FileUpload/index.vue

array.at()方法对浏览器版本要求还是有点高，低版本chrome选择文件后界面没反应
建议更换为兼容性更好的array.slice(-1).join()

**Comment by hooray** [comment]
开发环境建议使用 chrome 最新版本，生产环境可以通过 `@vitejs/plugin-legacy` 处理
https://github.com/fantastic-admin/basic/blob/example/vite/plugins/index.ts#L21-L27
