### ISSUE TITLE
极力推荐支持现代化的css框架

### ISSUE THREAD

**Issue by lyric-zemin** [fantastic-admin/basic#22]
感谢作者开源这么好用的中后台模板

在体验的过程中唯一缺憾的就是未能支持现代化的css框架，类似 `UnoCSS`，`Tailwind CSS`。

作者有计划支持吗😁

**Comment by hooray** [comment]
开发者可以根据自身的需要去引入这类原子化 CSS 库，框架因为有一部分历史包袱原因，目前不会考虑引入并重构，但这并不妨碍开发者在业务页面内开发使用。
