### ISSUE TITLE
在模板使用断言导致vscode代码颜色异常

### ISSUE THREAD

**Issue by shuTwT** [fantastic-admin/basic#24]
<img width="316" alt="image" src="https://github.com/fantastic-admin/basic/assets/95295076/b33332c3-fc40-4ff9-8b1b-713e7b8ed57e">
<img width="574" alt="image" src="https://github.com/fantastic-admin/basic/assets/95295076/13e4e5dc-6266-4044-b222-72bf5ced3d0d">

**Comment by F-OlO-Y** [comment]
添加()包裹
