### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by JaKajiajiajia** [fantastic-admin/basic#27]
请问是否可以考虑 JavaScript 版本吗

**Comment by JaKajiajiajia** [comment]
请问是否可以考虑 JavaScript 版本吗

**Comment by hooray** [comment]
不会提供 JS 版本，如果对 TS 不熟悉，可以参考[此处](https://fantastic-admin.gitee.io/guide/q-a.html#%E4%B8%8D%E4%BC%9A-typescript-%E6%80%8E%E4%B9%88%E5%8A%9E)的设置
