### ISSUE TITLE
settings.ts引入lodash-es时无法找到模块“lodash-es”的声明文件

### ISSUE THREAD

**Issue by vaecou** [fantastic-admin/basic#33]
![image](https://github.com/fantastic-admin/basic/assets/32005908/78081765-93cd-4f83-8a58-78c275673ea2)

**Comment by hooray** [comment]
框架有安装 `@types/lodash-es` 包，应该不会出现这个警告，你可以尝试开启 [volar takeover](https://fantastic-admin.gitee.io/guide/ready.html#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83) 模式

**Comment by vaecou** [comment]
> 框架有安装 `@types/lodash-es` 包，应该不会出现这个警告，你可以尝试开启 [volar takeover](https://fantastic-admin.gitee.io/guide/ready.html#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83) 模式

已经开启过了
