### ISSUE TITLE
开源版本支持二开吧？

### ISSUE THREAD

**Issue by GreatAuk** [fantastic-admin/basic#36]
看开源协议是 `MIT`, 但看你文档又说用 basic 版本，要保留框架版权信息。 
<img width="786" alt="image" src="https://github.com/fantastic-admin/basic/assets/20253809/d5c44d1f-b4e5-4487-8080-847dd471ab46">

**Comment by hooray** [comment]
可以二开，两者并不冲突，并且 MIT 协议本身也只要求保留版权信息，除此之外没有任何限制。

> MIT开源协议是一种宽松的开源许可证，允许软件在保留版权和许可证声明的前提下，免费使用、复制、修改、合并、出版、分发、再授权和销售等。
