### ISSUE TITLE
vscode 插件更新

### ISSUE THREAD

**Issue by hanyoujun** [fantastic-admin/basic#37]
Vue Language Features 升级到2.0
TypeScript Vue Plugin (Volar) 弃用了

tsconfig.json 需要对应修改

"include": [
  "./src/*.ts",
  "./src/*.vue",
  "./src/*.ext",
]

**Comment by hooray** [comment]
https://github.com/fantastic-admin/basic/commit/f26b4cc50e25feee850056aa120a36c4a09ff0a6
已经移除相关扩展推荐了，下次发版会更新

另外 tsconfig.json 不需要修改吧
