### ISSUE TITLE
文档中描述的breadcrumb配置不支持

### ISSUE THREAD

**Issue by chaegumi** [fantastic-admin/basic#38]
https://fantastic-admin.github.io/v3-docs/guide/breadcrumb.html#%E6%98%BE%E7%A4%BA%E4%B8%BB%E5%AF%BC%E8%88%AA

```
const globalSettings: Settings.all = {
  breadcrumb: {
    enableMainMenu: true,
  },
}
```

**Comment by chaegumi** [comment]
当使用文件系统路由时，将无法使用面包屑导航

**Comment by chaegumi** [comment]
```
const globalSettings: Settings.all = {
  app: {
    enableAppSetting: true,
  },
}
```
这个也不支持

**Comment by chaegumi** [comment]
> ```
> const globalSettings: Settings.all = {
>   app: {
>     enableAppSetting: true,
>   },
> }
> ```
> 
> 这个也不支持

这个我看源码可以在.env文件中修改

**Comment by hooray** [comment]
你看的文档不对，这是 v3 版本历史文档，要看官网最新的文档 https://fantastic-admin.github.io/
