### ISSUE TITLE
基于文件系统的路由的疑问

### ISSUE THREAD

**Issue by youngledo** [fantastic-admin/basic#47]
文档中说“启用基于文件系统的路由后，/src/router/modules/ 目录将不再被需要，而 /src/views/ 目录下的文件会自动被注册成路由。”

既然不需要，为什么删除`/src/router/`目录删除后就无法进入呢？

**Comment by hooray** [comment]
`/src/router/modules/` 目录不需要，`/src/router/` 还是需要的

**Comment by youngledo** [comment]
我试过`modules/`也不能删除，删了就进不去。

**Comment by youngledo** [comment]
另外我发现删了后修改mock数据怎么改都不变，这是什么原因
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/5a570fe6-5eac-41c3-bdea-4b07cbe284b7">

**Comment by youngledo** [comment]
经过严重，发现从后端获取数据（mock）必须要重新执行`pnpm run dev`才能生效，否则mock的数据永远不变，这是什么情况？

**Comment by hooray** [comment]
> 经过验证，发现从后端获取数据（mock）必须要重新执行`pnpm run dev`才能生效，否则mock的数据永远不变，这是什么情况？

测试发现是上游 vite-plugin-fake-server 的问题，https://github.com/condorheroblog/vite-plugin-fake-server/issues/38

**Comment by hooray** [comment]
已修复，可拉取最新源码，或者手动更新 vite-plugin-fake-server 到 2.1.4
